/*
 * NewsCatcher News API V2
 *
 * NewsCatcher is a data-as-a-service startup that has one main goal: to build the largest database of structured news articles published online. In other words, we're like Google for the news part of the web, which you can access as a source of data.  Some useful links: - [How NewsCatcher Works](https://docs.newscatcherapi.com/knowledge-base/how-newscatcher-works) - [GitHub for the Python SDK](https://github.com/NewscatcherAPI/newscatcherapi-sdk-python) 
 *
 * The version of the OpenAPI document: 1.0.1
 * Contact: team@newscatcherapi.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Newscatcherapi.Net.Api;
using Newscatcherapi.Net.Model;
using Newscatcherapi.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Newscatcherapi.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Model200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Model200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Model200Response
        //private Model200Response instance;

        public Model200ResponseTests()
        {
            // TODO uncomment below to create an instance of Model200Response
            //instance = new Model200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Model200Response
        /// </summary>
        [Fact]
        public void Model200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" Model200Response
            //Assert.IsType<Model200Response>(instance);
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'TotalHits'
        /// </summary>
        [Fact]
        public void TotalHitsTest()
        {
            // TODO unit test for the property 'TotalHits'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'TotalPages'
        /// </summary>
        [Fact]
        public void TotalPagesTest()
        {
            // TODO unit test for the property 'TotalPages'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'Articles'
        /// </summary>
        [Fact]
        public void ArticlesTest()
        {
            // TODO unit test for the property 'Articles'
        }
        /// <summary>
        /// Test the property 'UserInput'
        /// </summary>
        [Fact]
        public void UserInputTest()
        {
            // TODO unit test for the property 'UserInput'
        }

    }

}
