/*
 * NewsCatcher-V3 Production API
 *
 * <img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>
 *
 * The version of the OpenAPI document: 3.2.16
 * Contact: maksym@newscatcherapi.com
 * Generated by: https://konfigthis.com
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Newscatcherapi.Net.Api;
using Newscatcherapi.Net.Model;
using Newscatcherapi.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Newscatcherapi.Net.Test.Model
{
    /// <summary>
    ///  Class for testing DuplicatesByOriginalIdRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Konfig (https://konfigthis.com).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DuplicatesByOriginalIdRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DuplicatesByOriginalIdRequest
        //private DuplicatesByOriginalIdRequest instance;

        public DuplicatesByOriginalIdRequestTests()
        {
            // TODO uncomment below to create an instance of DuplicatesByOriginalIdRequest
            //instance = new DuplicatesByOriginalIdRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DuplicatesByOriginalIdRequest
        /// </summary>
        [Fact]
        public void DuplicatesByOriginalIdRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DuplicatesByOriginalIdRequest
            //Assert.IsType<DuplicatesByOriginalIdRequest>(instance);
        }


        /// <summary>
        /// Test the property 'OriginalArticleId'
        /// </summary>
        [Fact]
        public void OriginalArticleIdTest()
        {
            // TODO unit test for the property 'OriginalArticleId'
        }
        /// <summary>
        /// Test the property 'Page'
        /// </summary>
        [Fact]
        public void PageTest()
        {
            // TODO unit test for the property 'Page'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }

    }

}
