/*
 * NewsCatcher-V3 Production API
 * <img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>
 *
 * The version of the OpenAPI document: Beta-3.0.0
 * Contact: maksym@newscatcherapi.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.newscatcherapi.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.newscatcherapi.client.model.ArticlesPropertyInner;
import com.konfigthis.newscatcherapi.client.model.Cluster1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CSLHFResponse
 */
public class CSLHFResponseTest {
    private final CSLHFResponse model = new CSLHFResponse();

    /**
     * Model tests for CSLHFResponse
     */
    @Test
    public void testCSLHFResponse() {
        // TODO: test CSLHFResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'totalHits'
     */
    @Test
    public void totalHitsTest() {
        // TODO: test totalHits
    }

    /**
     * Test the property 'page'
     */
    @Test
    public void pageTest() {
        // TODO: test page
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    public void totalPagesTest() {
        // TODO: test totalPages
    }

    /**
     * Test the property 'pageSize'
     */
    @Test
    public void pageSizeTest() {
        // TODO: test pageSize
    }

    /**
     * Test the property 'clustersCount'
     */
    @Test
    public void clustersCountTest() {
        // TODO: test clustersCount
    }

    /**
     * Test the property 'clusters'
     */
    @Test
    public void clustersTest() {
        // TODO: test clusters
    }

    /**
     * Test the property 'userInput'
     */
    @Test
    public void userInputTest() {
        // TODO: test userInput
    }

    /**
     * Test the property 'articles'
     */
    @Test
    public void articlesTest() {
        // TODO: test articles
    }

}
