/* tslint:disable */
/* eslint-disable */
/*
NewsCatcher-V3 Production API

<img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>

The version of the OpenAPI document: 3.2.16
Contact: maksym@newscatcherapi.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { SourceResponse } from '../models';
// @ts-ignore
import { SourcesRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * SourcesApi - axios parameter creator
 * @export
 */
export const SourcesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Get] Search For Sources Request
         * @param {any} [lang] 
         * @param {any} [countries] 
         * @param {any} [predefinedSources] 
         * @param {boolean} [includeAdditionalInfo] 
         * @param {number} [fromRank] 
         * @param {number} [toRank] 
         * @param {any} [sourceName] 
         * @param {any} [sourceUrl] 
         * @param {boolean} [isNewsDomain] 
         * @param {any} [newsDomainType] 
         * @param {any} [newsType] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (lang?: any, countries?: any, predefinedSources?: any, includeAdditionalInfo?: boolean, fromRank?: number, toRank?: number, sourceName?: any, sourceUrl?: any, isNewsDomain?: boolean, newsDomainType?: any, newsType?: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/sources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-token", keyParamName: "xApiToken", configuration })
            if (lang !== undefined) {
                localVarQueryParameter['lang'] = lang;
            }

            if (countries !== undefined) {
                localVarQueryParameter['countries'] = countries;
            }

            if (predefinedSources !== undefined) {
                localVarQueryParameter['predefined_sources'] = predefinedSources;
            }

            if (includeAdditionalInfo !== undefined) {
                localVarQueryParameter['include_additional_info'] = includeAdditionalInfo;
            }

            if (fromRank !== undefined) {
                localVarQueryParameter['from_rank'] = fromRank;
            }

            if (toRank !== undefined) {
                localVarQueryParameter['to_rank'] = toRank;
            }

            if (sourceName !== undefined) {
                localVarQueryParameter['source_name'] = sourceName;
            }

            if (sourceUrl !== undefined) {
                localVarQueryParameter['source_url'] = sourceUrl;
            }

            if (isNewsDomain !== undefined) {
                localVarQueryParameter['is_news_domain'] = isNewsDomain;
            }

            if (newsDomainType !== undefined) {
                localVarQueryParameter['news_domain_type'] = newsDomainType;
            }

            if (newsType !== undefined) {
                localVarQueryParameter['news_type'] = newsType;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/sources',
                httpMethod: 'GET'
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Post] Search For Sources Request
         * @param {SourcesRequest} sourcesRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        post: async (sourcesRequest: SourcesRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourcesRequest' is not null or undefined
            assertParamExists('post', 'sourcesRequest', sourcesRequest)
            const localVarPath = `/api/sources`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKey required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "x-api-token", keyParamName: "xApiToken", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: sourcesRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/api/sources',
                httpMethod: 'POST'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(sourcesRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SourcesApi - functional programming interface
 * @export
 */
export const SourcesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SourcesApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Get] Search For Sources Request
         * @param {SourcesApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(requestParameters: SourcesApiGetRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SourceResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(requestParameters.lang, requestParameters.countries, requestParameters.predefinedSources, requestParameters.includeAdditionalInfo, requestParameters.fromRank, requestParameters.toRank, requestParameters.sourceName, requestParameters.sourceUrl, requestParameters.isNewsDomain, requestParameters.newsDomainType, requestParameters.newsType, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Post] Search For Sources Request
         * @param {SourcesApiPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async post(requestParameters: SourcesApiPostRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SourceResponse>> {
            const sourcesRequest: SourcesRequest = {
                lang: requestParameters.lang,
                countries: requestParameters.countries,
                predefined_sources: requestParameters.predefined_sources,
                include_additional_info: requestParameters.include_additional_info,
                from_rank: requestParameters.from_rank,
                to_rank: requestParameters.to_rank,
                source_name: requestParameters.source_name,
                source_url: requestParameters.source_url,
                is_news_domain: requestParameters.is_news_domain,
                news_domain_type: requestParameters.news_domain_type,
                news_type: requestParameters.news_type
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.post(sourcesRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * SourcesApi - factory interface
 * @export
 */
export const SourcesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SourcesApiFp(configuration)
    return {
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Get] Search For Sources Request
         * @param {SourcesApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: SourcesApiGetRequest = {}, options?: AxiosRequestConfig): AxiosPromise<SourceResponse> {
            return localVarFp.get(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
         * @summary [Post] Search For Sources Request
         * @param {SourcesApiPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        post(requestParameters: SourcesApiPostRequest, options?: AxiosRequestConfig): AxiosPromise<SourceResponse> {
            return localVarFp.post(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for get operation in SourcesApi.
 * @export
 * @interface SourcesApiGetRequest
 */
export type SourcesApiGetRequest = {
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly lang?: any
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly countries?: any
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly predefinedSources?: any
    
    /**
    * 
    * @type {boolean}
    * @memberof SourcesApiGet
    */
    readonly includeAdditionalInfo?: boolean
    
    /**
    * 
    * @type {number}
    * @memberof SourcesApiGet
    */
    readonly fromRank?: number
    
    /**
    * 
    * @type {number}
    * @memberof SourcesApiGet
    */
    readonly toRank?: number
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly sourceName?: any
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly sourceUrl?: any
    
    /**
    * 
    * @type {boolean}
    * @memberof SourcesApiGet
    */
    readonly isNewsDomain?: boolean
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly newsDomainType?: any
    
    /**
    * 
    * @type {any}
    * @memberof SourcesApiGet
    */
    readonly newsType?: any
    
}

/**
 * Request parameters for post operation in SourcesApi.
 * @export
 * @interface SourcesApiPostRequest
 */
export type SourcesApiPostRequest = {
    
} & SourcesRequest

/**
 * SourcesApiGenerated - object-oriented interface
 * @export
 * @class SourcesApiGenerated
 * @extends {BaseAPI}
 */
export class SourcesApiGenerated extends BaseAPI {
    /**
     * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
     * @summary [Get] Search For Sources Request
     * @param {SourcesApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourcesApiGenerated
     */
    public get(requestParameters: SourcesApiGetRequest = {}, options?: AxiosRequestConfig) {
        return SourcesApiFp(this.configuration).get(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint allows you to get the list of sources that are available in the database. You can filter the sources by language and country. The maximum number of sources displayed is set according to your plan. You can find the list of plans and their features here: https://newscatcherapi.com/news-api#news-api-pricing
     * @summary [Post] Search For Sources Request
     * @param {SourcesApiPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof SourcesApiGenerated
     */
    public post(requestParameters: SourcesApiPostRequest, options?: AxiosRequestConfig) {
        return SourcesApiFp(this.configuration).post(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
