/*
NewsCatcher-V3 Production API

<img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>

The version of the OpenAPI document: 3.2.16
Contact: maksym@newscatcherapi.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { SourcesPropertyInner } from './sources-property-inner';

/**
 * SourceResponse DTO class.
 * @export
 * @interface SourceResponse
 */
export interface SourceResponse {
    /**
     * 
     * @type {string}
     * @memberof SourceResponse
     */
    'message': string;
    /**
     * 
     * @type {Array<SourcesPropertyInner>}
     * @memberof SourceResponse
     */
    'sources': Array<SourcesPropertyInner>;
    /**
     * 
     * @type {object}
     * @memberof SourceResponse
     */
    'user_input': object;
}

