# coding: utf-8

"""
    NewsCatcher-V3 Production API

    <img src='https://uploads-ssl.webflow.com/6429857b17973b636c2195c5/646c6f1eb774ff2f2997bec5_newscatcher_.svg' width='286' height='35' /> <br>  <br>Visit our website  <a href='https://newscatcherapi.com'>https://newscatcherapi.com</a>

    The version of the OpenAPI document: 3.2.16
    Contact: maksym@newscatcherapi.com
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import newscatcherapi_client
from newscatcherapi_client.paths.api_latest_headlines import get
from newscatcherapi_client import configuration, schemas, api_client

from .. import ApiTestMixin


class TestApiLatestHeadlines(ApiTestMixin, unittest.TestCase):
    """
    ApiLatestHeadlines unit test stubs
        [Get] Search For Latest Headlines Request
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
